# Data Preprocessing | Machine Learning Bootcamp

## Import the required libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [2]:
dataset= pd.read_csv('Data.csv')
x=dataset.iloc[ : ,:-1].values
y=dataset.iloc[:,-1].values

## Solving for missing data

In [3]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values = np.nan , strategy ='mean')
imputer.fit(x[:, 1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

## Encoding categorical data

### Encoding the Independent Variable

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

Column_transform = ColumnTransformer ( transformers= [('encoder' , OneHotEncoder(), [0]),], remainder ='passthrough' )
x=np.array(Column_transform.fit_transform(x))


### Encoding the dependent Variable

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_Test =train_test_split(x , y, test_size = 0.2 , random_state=40)


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
x_train = scaler.fit_transform(x_train)  
x_test = scaler.transform(x_test)  
print(x)
print(y)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]
[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]
